# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ttkd_api.Person'),
            preserve_default=False,
        ),
    ]
