# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0003_auto_20161007_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='ttkd_api.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_number',
            field=models.CharField(default='555-555-5555', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relation',
            field=models.CharField(default='Father', max_length=30),
            preserve_default=False,
        ),
    ]
