# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0004_auto_20161010_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='full_name',
            field=models.CharField(default='Spongebob Sqaurepants', max_length=100),
            preserve_default=False,
        ),
    ]
