# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0005_emergencycontact_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
