# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0006_auto_20161012_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
