# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0007_auto_20161016_1544'),
        ('ttkd_api', '0007_auto_20161013_1721'),
    ]

    operations = [
    ]
