# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0009_auto_20161021_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belt',
            name='num_strips',
        ),
        migrations.RemoveField(
            model_name='person',
            name='extra_strips',
        ),
        migrations.RemoveField(
            model_name='person',
            name='stripes',
        ),
    ]
