# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0010_auto_20161026_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonStripe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripes', to='ttkd_api.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Stripe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('belt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttkd_api.Belt')),
            ],
        ),
        migrations.AddField(
            model_name='personstripe',
            name='stripe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttkd_api.Stripe'),
        ),
    ]
