# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0011_auto_20161026_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonBelt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achieved', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='belt',
            name='order',
        ),
        migrations.RemoveField(
            model_name='person',
            name='belt',
        ),
        migrations.RemoveField(
            model_name='stripe',
            name='belt',
        ),
        migrations.AddField(
            model_name='belt',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personstripe',
            name='date_achieved',
            field=models.DateField(default=datetime.date(2016, 10, 28)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripe',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stripe',
            name='color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='personbelt',
            name='Belt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttkd_api.Belt'),
        ),
        migrations.AddField(
            model_name='personbelt',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Belts', to='ttkd_api.Person'),
        ),
    ]
