# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0012_auto_20161028_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personbelt',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belts', to='ttkd_api.Person'),
        ),
    ]
