# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0016_auto_20161028_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personbelt',
            options={'ordering': ('-date_achieved', '-belt')},
        ),
        migrations.RenameField(
            model_name='personbelt',
            old_name='Belt',
            new_name='belt',
        ),
    ]
