# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0017_auto_20161028_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personbelt',
            options={},
        ),
        migrations.AddField(
            model_name='personbelt',
            name='current_belt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personstripe',
            name='current_stripe',
            field=models.BooleanField(default=True),
        ),
    ]
