# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0018_auto_20161028_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='emergency_contact_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_1', to='ttkd_api.EmergencyContact'),
        ),
        migrations.AddField(
            model_name='person',
            name='emergency_contact_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_2', to='ttkd_api.EmergencyContact'),
        ),
    ]
