# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0021_auto_20161103_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='picture_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
