# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0022_auto_20161108_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='picture_path',
        ),
    ]
