# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0023_auto_20161110_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belt',
            name='name',
            field=models.CharField(default='Yellow', max_length=25),
            preserve_default=False,
        ),
    ]
