# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import ttkd_api.models.person


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0024_person_picture_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='picture_path',
        ),
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=ttkd_api.models.person.Person.upload_to, verbose_name='picture'),
        ),
    ]
