# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0025_auto_20161110_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture_url',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
