# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0026_person_picture_url'),
        ('ttkd_api', '0024_auto_20161110_1807'),
    ]

    operations = [
    ]
