# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0028_auto_20161129_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='guardian_signature',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='signature_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='waiver_signature',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
