# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0029_auto_20170110_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='guardian_signature',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='signature_timestamp',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='waiver_signature',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
