# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0030_auto_20170111_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='belt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belt', to='ttkd_api.Belt'),
        ),
    ]
