# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0031_person_belt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personbelt',
            name='current_belt',
        ),
    ]
