# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ttkd_api.models.waiver


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0032_remove_personbelt_current_belt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiver_signature', models.CharField(blank=True, max_length=60, null=True)),
                ('guardian_signature', models.CharField(blank=True, max_length=60, null=True)),
                ('signature_timestamp', models.DateTimeField(auto_now=True)),
                ('waiver_image', models.ImageField(blank=True, null=True, upload_to=ttkd_api.models.waiver.Waiver.upload_to, verbose_name='waiver_image')),
                ('waiver_url', models.CharField(blank=True, max_length=2083, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='ttkd_api.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='guardian_signature',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='signature_timestamp',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='waiver_signature',
        ),
    ]
