# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0034_auto_20170214_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='partial',
            new_name='is_partial',
        ),
    ]
