# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0035_auto_20170216_1032'),
        ('ttkd_api', '0033_auto_20170212_2133'),
    ]

    operations = [
    ]
