# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0037_auto_20170219_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttkd_api.Person')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttkd_api.Program')),
            ],
        ),
    ]
