# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0039_auto_20170303_1952'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set([('person', 'program', 'date')]),
        ),
    ]
