# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttkd_api', '0041_auto_20170309_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='street',
            field=models.CharField(blank=True, max_length=95, null=True),
        ),
    ]
